# -*- coding: utf-8 -*-
"""PREGUNTA 19

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wgu5kQ5NYEXohB_zvsQyaovdtj1ukzMa
"""

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller, kpss

# === 1. Cargar archivo Excel ===
archivo = '22.7.xlsx'  # Asegúrate de que esté en tu carpeta de trabajo
df = pd.read_excel(archivo)

# Ajustar nombres de columna si es necesario
df.columns = ['Index', 'TB3M', 'TB6M']

# Crear una serie de fechas (mensual) desde enero 1982
df['Date'] = pd.date_range(start='1982-01-01', periods=len(df), freq='M')
df.set_index('Date', inplace=True)

# === 2. Análisis Estadístico Descriptivo ===
print("Análisis estadístico descriptivo:")
print(df[['TB3M', 'TB6M']].describe())

# === 3. Graficar ambas series en el mismo diagrama ===
plt.figure(figsize=(12, 6))
plt.plot(df['TB3M'], label='TB3M - 3-Month T-Bill', color='blue')
plt.plot(df['TB6M'], label='TB6M - 6-Month T-Bill', color='red', linestyle='--')
plt.title('Tasas de Letras del Tesoro (TB3M vs TB6M)', fontsize=14)
plt.xlabel('Fecha', fontsize=12)
plt.ylabel('Tasa (%)', fontsize=12)
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# === 4. Análisis de Tendencia (Media Móvil) ===
df['TB3M_MA'] = df['TB3M'].rolling(window=12).mean()  # Media móvil de 12 meses
df['TB6M_MA'] = df['TB6M'].rolling(window=12).mean()

plt.figure(figsize=(12, 6))
plt.plot(df['TB3M'], label='TB3M - 3-Month T-Bill', color='blue', alpha=0.6)
plt.plot(df['TB6M'], label='TB6M - 6-Month T-Bill', color='red', alpha=0.6)
plt.plot(df['TB3M_MA'], label='Media Móvil TB3M', color='blue', linestyle='--', linewidth=2)
plt.plot(df['TB6M_MA'], label='Media Móvil TB6M', color='red', linestyle='--', linewidth=2)
plt.title('Tasas de Letras del Tesoro con Media Móvil (12 meses)', fontsize=14)
plt.xlabel('Fecha', fontsize=12)
plt.ylabel('Tasa (%)', fontsize=12)
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# === 5. Correlación entre TB3M y TB6M ===
correlacion = df[['TB3M', 'TB6M']].corr()
print("\nCorrelación entre TB3M y TB6M:")
print(correlacion)

# === 6. Prueba de raíz unitaria (ADF) ===
def prueba_adf(serie, nombre):
    resultado = adfuller(serie.dropna(), autolag='AIC')
    print(f'\n📊 ADF Test para {nombre}')
    print(f'Estadístico ADF: {resultado[0]:.4f}')
    print(f'Valor p: {resultado[1]:.4f}')
    print(f'Número de rezagos utilizados: {resultado[2]}')
    print(f'Número de observaciones usadas: {resultado[3]}')
    print('Valores críticos:')
    for clave, valor in resultado[4].items():
        print(f'  {clave}: {valor:.4f}')
    if resultado[1] < 0.05:
        print(f'✅ La serie {nombre} es estacionaria (se rechaza H0 de raíz unitaria).')
    else:
        print(f'❌ La serie {nombre} NO es estacionaria (no se rechaza H0).')

# Ejecutar prueba ADF para cada serie
prueba_adf(df['TB3M'], 'TB3M')
prueba_adf(df['TB6M'], 'TB6M')



# === 7. Prueba de estacionariedad KPSS ===
def prueba_kpss(serie, nombre):
    # Cambié 'lags' por 'nlags' para usar el argumento correcto
    resultado = kpss(serie.dropna(), regression='c', nlags='auto')
    print(f'\n📊 KPSS Test para {nombre}')
    print(f'Estadístico KPSS: {resultado[0]:.4f}')
    print(f'Valor p: {resultado[1]:.4f}')
    if resultado[1] < 0.05:
        print(f'❌ La serie {nombre} NO es estacionaria (se rechaza H0 de estacionariedad).')
    else:
        print(f'✅ La serie {nombre} es estacionaria (no se rechaza H0).')

# Ejecutar prueba KPSS para cada serie
prueba_kpss(df['TB3M'], 'TB3M')
prueba_kpss(df['TB6M'], 'TB6M')

# === 8. Análisis de Volatilidad (Desviación estándar mensual) ===
df['TB3M_vol'] = df['TB3M'].rolling(window=12).std()  # Desviación estándar de 12 meses
df['TB6M_vol'] = df['TB6M'].rolling(window=12).std()

plt.figure(figsize=(12, 6))
plt.plot(df['TB3M_vol'], label='Volatilidad TB3M', color='blue')
plt.plot(df['TB6M_vol'], label='Volatilidad TB6M', color='red', linestyle='--')
plt.title('Volatilidad de las Tasas de Letras del Tesoro (12 meses)', fontsize=14)
plt.xlabel('Fecha', fontsize=12)
plt.ylabel('Volatilidad', fontsize=12)
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()